CREATE TABLE IF NOT EXISTS services (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  owner VARCHAR(100) NOT NULL,
  tier SMALLINT NOT NULL DEFAULT 3 CHECK (tier BETWEEN 1 AND 4),
  status VARCHAR(20) NOT NULL DEFAULT 'OPERATIONAL'
    CHECK (status IN ('OPERATIONAL', 'DEGRADED', 'OUTAGE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS incidents (
  id SERIAL PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  description TEXT,
  severity VARCHAR(10) NOT NULL CHECK (severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')),
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN'
    CHECK (status IN ('OPEN', 'INVESTIGATING', 'MONITORING', 'RESOLVED')),
  service_id INTEGER NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  assignee VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_severity ON incidents(severity);
CREATE INDEX IF NOT EXISTS idx_incidents_service_id ON incidents(service_id);

